# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=50)),
                ('risk_code', models.CharField(max_length=5, unique=True)),
                ('risk_attr_meta', models.TextField(default=[{'display_title': 'First Name', 'field_name': 'first_name', 'field_type': 'text'}, {'display_title': 'Last Name', 'field_name': 'last_name', 'field_type': 'text'}, {'display_title': 'Serial NO', 'field_name': 'serial_no', 'field_type': 'text'}])),
            ],
        ),
    ]
